apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test 
  janus-idp.io/tekton: test
  backstage.io/kubernetes-id: test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  